In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
g = np.array([['a', 'b'], 
             ['c', 'd']], dtype='|S1')
g

array([[b'a', b'b'],
       [b'c', b'd']], dtype='|S1')

In [4]:
g.dtype

dtype('S1')

In [6]:
g.dtype.name

'bytes8'

In [9]:
z = np.zeros((3, 3))
z.dtype
z.dtype.name


'float64'

In [17]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [25]:
np.random.random((3, 4))

array([[0.34508617, 0.74913122, 0.56870001, 0.18999134],
       [0.64352361, 0.51227965, 0.20416754, 0.06953542],
       [0.80646282, 0.41718371, 0.2734461 , 0.76985471]])

In [26]:
np.arange(4) *4


array([ 0,  4,  8, 12])

In [28]:
a = np.random.random((4, 3))
b = np.random.random((3, 4))
np.dot(a, b)

array([[1.12710068, 0.72200143, 0.67154734, 1.33052018],
       [1.23597261, 0.82509414, 0.68014061, 1.37630483],
       [0.530198  , 0.47931954, 0.16448206, 0.5688467 ],
       [0.45826309, 0.24720287, 0.30167714, 0.48566325]])

In [30]:
b.dot(a)

array([[0.74394988, 0.92444152, 0.23440781],
       [1.30236824, 1.38296776, 0.43425788],
       [1.69553843, 1.97018802, 0.47542249]])

In [34]:
a.min()


0.024876623272827914

In [35]:
b.min()

0.13990426749520468

In [36]:
a

array([[0.98632853, 0.84379766, 0.04521431],
       [0.69285857, 0.82587253, 0.29587555],
       [0.39363062, 0.04101917, 0.34660535],
       [0.02487662, 0.44565752, 0.09152753]])

In [40]:
b = np.arange(2, 6)
b

array([2, 3, 4, 5])

In [41]:
b[3]

5

In [52]:
ar = []
for item in a.flat:
    print(item)

0.9863285274248346
0.8437976593077039
0.0452143141578043
0.6928585656847647
0.8258725314343378
0.2958755531265552
0.3936306203470922
0.041019172032553786
0.3466053537700686
0.024876623272827914
0.44565751553832744
0.09152753284231308
